### PR TITLE
Run Expectation Extension

### PR DESCRIPTION
**Pull request by pmisteliac**

### CODE REVIEW

**Review by Apanatshka — CHANGES_REQUESTED** [review]
I'm seeing inconsistent indentation, mixes of tabs and spaces. Please fix that.
`mbt.core` was designed explicitly to not depend on Spoofax. If you need `IStrategoTerm` in `RunStrategoExpectation`, you should move it to `spt.core` where `RunStrategoToAtermExpectation` lives for the same reason. 
`RunStrategoExpectationProvider` was very difficult to review because of all the whitespace changes. Please check the changes next time you try to autoformat a file, and don't apply them if they change basically the entire file.

**Review by pmisteliac — COMMENTED** [review]
Apologies for the messed up formatting, the old tab vs. spaces conflict at its best.
I moved the Expecation value object and reverted the changes in the POM.

**Review by Apanatshka — APPROVED** [review]

**Comment by Virtlink** [comment]
Depends on metaborg/spoofax#74

**Comment by Virtlink** [comment]
Depends on metaborg/mb-exec#10

**Pull request merged**
